---
env: 'docker'
mixAmtEth: 0.1
mixAmtTokens: 20
feeAmtEth: 0.001
feeAmtTokens: 2
tokenSym: 'DAI'
tokenDecimals: 18

chain:
  url: "https://kovan.infura.io/v3/5d37c494621a43558d77c90e368d4022"
  chainId: 42
  mix:
    gasLimit: 500000
  privateKeysPath: "../kovanPrivateKeys.json"
  deployedAddresses:
    MiMC: '0x4e8E48FE6D2A6eec138269a92085b1110C8A763D'
    Semaphore: '0x341B0D9B7ac18067fF1a99D9265c33Ae29ECdbf7'
    Mixer: '0xecaFa9BE8fc203a064aFb04dbe53f98E55ddFBD1'
    TokenMixer: '0x12E12EFD0046613F35Ac82406a0b429E16F258dd'
    TokenSemaphore: '0x2d789d11E697bF39Ca3d9C07F565C9065DD02542'
    RelayerRegistry: '0xb080FCf2c1ABDa24e161AD68D338b4DEF3073d02'
    Token: '0xc4375b7de8af5a38a93548eb8453a498222c4ff2'

backend:
  port: 3000
  host: "http://localhost"
  hotWalletPrivKeyPath: "/run/secrets/hotWalletPrivKeyPath"
  relayerAddress: "0x53BE836678eA3Dbf7257ef32954184Ac06C2D4b1"
  etcd:
    host: "mixer-etcd"
    port: 2379
    lockTime: 7000

frontend:
  snarks:
    paths:
      verificationKey: 'https://micromixtest.blob.core.windows.net/snarks/verification_key.json'
      provingKey: 'https://micromixtest.blob.core.windows.net/snarks/proving_key.bin'
      circuit: 'https://micromixtest.blob.core.windows.net/snarks/circuit.json'
  countdown:
    endsAtUtcMidnight: true
    endsAfterSecs: 5
  supportedNetworkName: "Kovan"
  supportedNetwork: 42
  blockExplorerTxPrefix: "https://kovan.etherscan.io/tx/"
